# Generated by Django 2.1.5 on 2019-03-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='facts',
            new_name='fact',
        ),
    ]
